# ./.tmuxinator.yml

name: klippy
root: ~/

windows:
  - editor:
      layout: main-vertical
      panes:
        - klippy-log:
          - less --follow-name +F /tmp/klippy.log
        - gcode-out:
          - less --follow-name -f +F /tmp/printer
        - gcode-in:
          - gcodeLoop
